"use client"

import Link from "next/link"
import { FormEvent, useEffect, useState } from "react"
import { changeUsername, confirmEmailChange, deleteAccount, getSettings, requestAffiliateWithdrawal, startEmailChange } from "@/lib/api"
import { clientLogout, isLoggedIn } from "@/lib/auth-client"

export default function SettingsPage() {
  const [data, setData] = useState<any>(null), [error, setError] = useState(""), [notice, setNotice] = useState("")
  const reload = () => getSettings().then(setData).catch((e) => setError(e.message))
  useEffect(() => { if (isLoggedIn()) reload() }, [])
  if (!isLoggedIn()) return <main className="mx-auto max-w-2xl px-5 py-28"><h1 className="text-2xl font-bold">Settings</h1><p className="mt-3">Please <Link className="underline" href="/login?next=/settings">sign in</Link> to manage your account.</p></main>
  const submit = async (fn: () => Promise<any>) => { setError(""); setNotice(""); try { await fn(); setNotice("Saved."); reload() } catch (e) { setError(e instanceof Error ? e.message : "Request failed") } }
  const a = data?.affiliate
  return <main className="mx-auto max-w-3xl space-y-8 px-5 py-24"><div><h1 className="text-3xl font-bold">Settings</h1><p className="text-sm text-foreground/60">Manage your profile, affiliate rewards, and account.</p></div>{error && <p className="rounded border border-red-400 p-3 text-red-700">{error}</p>}{notice && <p className="rounded border border-emerald-400 p-3 text-emerald-700">{notice}</p>}
    {!data ? <p>Loading…</p> : <><section className="space-y-3 rounded-xl border p-5"><h2 className="text-xl font-semibold">Profile</h2><p>{data.user.name || data.user.username} · {data.user.email}</p><form onSubmit={(e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); submit(() => changeUsername(String(f.get("username")))) }} className="flex gap-2"><input name="username" defaultValue={data.user.username} className="min-w-0 flex-1 rounded border p-2"/><button className="rounded bg-black px-4 text-white">Change username</button></form></section>
    <section className="space-y-3 rounded-xl border p-5"><h2 className="text-xl font-semibold">Email</h2><form onSubmit={(e) => { e.preventDefault(); const f=new FormData(e.currentTarget); submit(() => startEmailChange(String(f.get("email")), String(f.get("password")))) }} className="grid gap-2 sm:grid-cols-3"><input name="email" type="email" placeholder="New email" className="rounded border p-2"/><input name="password" type="password" placeholder="Current password" className="rounded border p-2"/><button className="rounded bg-black px-4 py-2 text-white">Verify new email</button></form><form onSubmit={(e) => {e.preventDefault(); const f=new FormData(e.currentTarget); submit(() => confirmEmailChange(String(f.get("code"))))}} className="flex gap-2"><input name="code" placeholder="Verification code" className="flex-1 rounded border p-2"/><button className="rounded border px-4">Confirm</button></form></section>
    <section className="space-y-4 rounded-xl border p-5"><h2 className="text-xl font-semibold">Affiliate & rewards</h2><p>Invite link: <code className="break-all">{typeof window !== "undefined" ? `${window.location.origin}/signup?ref=${a.code}` : a.code}</code></p><div className="grid grid-cols-2 gap-3 text-sm sm:grid-cols-4"><Stat label="Invited" value={a.referrals}/><Stat label="Eligible" value={a.eligible_referrals}/><Stat label="Accepted books" value={a.accepted_books}/><Stat label="Available" value={`KES ${a.available_balance}`}/><Stat label="Earned" value={`KES ${a.earned}`}/><Stat label="Withdrawn" value={`KES ${a.withdrawn}`}/><Stat label="Invite reward" value={`KES ${a.referral_reward}`}/><Stat label="Minimum" value={`KES ${a.minimum_withdrawal}`}/></div><form onSubmit={(e) => {e.preventDefault(); const f=new FormData(e.currentTarget); submit(() => requestAffiliateWithdrawal(String(f.get("amount"))))}} className="flex gap-2"><input required name="amount" type="number" min="0.01" step="0.01" placeholder="Withdrawal amount" className="flex-1 rounded border p-2"/><button className="rounded bg-black px-4 text-white">Request withdrawal</button></form></section>
    <section className="space-y-3 rounded-xl border border-red-300 p-5"><h2 className="text-xl font-semibold text-red-700">Delete account</h2><p className="text-sm">This is consequential. Your public books remain in the library without ownership; financial audit records are retained.</p><form onSubmit={(e) => {e.preventDefault(); if (!confirm("Permanently delete your account?")) return; const f=new FormData(e.currentTarget); submit(async () => { const r=await deleteAccount({current_password:String(f.get("password")),reason:String(f.get("reason"))}); clientLogout(); location.href="/"; return r })}} className="grid gap-2"><input name="password" type="password" placeholder={data.user.password_auth ? "Current password" : "Google re-authentication is required by the backend"} className="rounded border p-2"/><textarea name="reason" placeholder="Reason (optional)" className="rounded border p-2"/><button className="w-fit rounded bg-red-700 px-4 py-2 text-white">Delete my account</button></form></section></>}</main>
}
function Stat({label,value}:{label:string,value:any}) { return <div className="rounded bg-foreground/5 p-3"><div className="text-foreground/60">{label}</div><strong>{value}</strong></div> }
